theme: jekyll-theme-minimal

# personal info
title: [YaoZhao]
description: [Master student, Fudan MICCAI lab]

author:
  name             : "YaoZhao"
  avatar           : "profile.jpeg"
  bio              : "Master student, Fudan MICCAI lab"
  location         : "Shang Hai" 
  employer         :
  email            : "y15216626501@gmail.com"